### ISSUE TITLE
cds

### ISSUE THREAD

**Issue by thirumal1** [AMekss/devise_custom_authenticatable#1]
I am getting the following error when I am using this gem.I need to implement custom authentication with a web service.

Processing by RootController#index as HTML
Completed 401 Unauthorized in 1ms (ActiveRecord: 0.0ms)

Thanks in advance
Rao

**Comment by thirumal1** [comment]
## Here is some log info if it helps

Without devise_custon_authenticable

Started GET "/users/sign_in" for 1xx.xx.xxx.xx at 2016-08-01 11:41:24 -0500
Processing by SessionsController#new as HTML
  Rendered devise/_links.erb (1.5ms)
  Rendered devise/sessions/new.html.erb within layouts/application (265.4ms)
  Rendered /usr/local/rvm/gems/ruby-1.9.3-p551/gems/govuk_admin_template-2.3.1/app/views/layouts/govuk_admin_template.html.erb (104.4ms)

## Completed 200 OK in 868ms (Views: 778.7ms | ActiveRecord: 2.7ms)

With devise_custon_authenticable

Started GET "/" for 1xx.xx.xxx.xx at 2016-08-01 11:41:24 -0500
Processing by RootController#index as HTML
Completed 401 Unauthorized in 0ms (ActiveRecord: 0.0ms)

**Comment by AMekss** [comment]
Hey @thirumal1, could you give me more insight on your environment, what versions of Rails/Devise are you using, what other plugins (if any) for Devise is enabled. A fragment of AR model where you setup Devise and enable `devise_custom_authenticatable` would also help.

**Comment by thirumal1** [comment]
Hi I was able to make it work.The issues was with the web service called within the custom authentication that was causing the problem( firewall issue).I am able to successfully use the gem.

Thanks for taking some time and responding to me.
