### ISSUE TITLE
change failed login message

### ISSUE THREAD

**Issue by bennyzr** [AMekss/devise_custom_authenticatable#6]
Hi,

How would I change the failed login flash message from the valid_for_custom_authentication?(password) method?

**Comment by janis-vitols** [comment]
Just guessing, but doesn't it uses default devise I18n locales? What kind of message you receive now on failed login? Maybe [this](https://github.com/plataformatec/devise/blob/master/config/locales/en.yml#L12) could help.

**Comment by bennyzr** [comment]
Right now I get the default "Invalid Email or password." message which is fine for the other strategies. For the custom strategy I would like to change the default message to a custom one. Or better yet specify the failure type so that I can use a custom message from the locales list.

**Comment by janis-vitols** [comment]
It looks like it's using default fail message [not_found_in_database](https://github.com/plataformatec/devise/blob/88724e10adaf9ffd1d8dbfbaadda2b9d40de756a/lib/devise/strategies/database_authenticatable.rb#L18).

I [don't see](https://github.com/AMekss/devise_custom_authenticatable/blob/master/lib/devise/strategies/custom_authenticatable.rb) an `#fail` method call in strategy `#authenticate!` method with different one (suppose it reuses default).

Maybe it could be implemented similarly as shown here in right answer on [stackoverflow](http://stackoverflow.com/questions/4223083/custom-authentication-strategy-for-devise), but that would mean that there need to be created PR and made some changes.

I would suggest to wait for AMekss answer, maybe I'm going totally wrong here :)

**Comment by AMekss** [comment]
@bennyzr Not sure its exactly what you need but you can override `#unauthenticated_message` of your "user" model. By default its [:invalid](https://github.com/plataformatec/devise/blob/master/lib/devise/models/authenticatable.rb#L84-L86) and is used by devise [here](https://github.com/plataformatec/devise/blob/master/lib/devise/strategies/authenticatable.rb#L42). I think (not 100% sure :) ) you can provide text message here and devise/warden will be smart enough to use it as is. Or you can return key (just like default `:invalid`) but then you have to put your translation where devise expect to have it `<locale>.devise.failure.<your_key>`
Hope this helps!

**Comment by AMekss** [comment]
To answer the original question you can have something like this
```ruby
class User < ActiveRecord::Base
#...
  def valid_for_custom_authentication?(password)
    # in the false branch of your custom auth logic
    @custom_unauthenticated_message = "your message or translation key"
  end
  
  def unauthenticated_message
    @custom_unauthenticated_message || super
  end
#...
end
```
It is not the cleanest implementation (as this invents some coupling between methods and state) however in the current implementation I'm afraid this is the best you can do.

**Comment by bennyzr** [comment]
Your second response was the solution I was searching for. Thanks.
