### ISSUE TITLE
adding :custom_authenticatable allows user record creation without password 

### ISSUE THREAD

**Issue by bennyzr** [AMekss/devise_custom_authenticatable#7]
Ever since I added :custom_authenticatable as a strategy to my User model all user records are being created without passwords.

**Comment by AMekss** [comment]
`:custom_authenticatable` doesn't relay on nor need stored passwords to authenticate the user instead it delegates this responsibility to out of bounds service like ActiveDirectory for example. 

While this module has nothing to do with user registration its hard to guess why it happens without having more details:
* how does your User model look like?
* what other authentication/devise related gems are you using?
* how does new user registration happens?
* do you have any customized devise controller?
* which versions of rails/devise are you using

**Comment by bennyzr** [comment]
There's nothing out of the ordinary about my User model. I only have devise strategies, model associations and some methods. No other authentication gems are being used. 

I am using the [ active admin gem ](https://github.com/activeadmin/activeadmin) to manage users. 

I am using rails 5.0.0.1 and devise 4.2.0.

**Comment by bennyzr** [comment]
I tried tracing this issue and so far only discovered that the attribute encrypted_password is not present in the mutation_tracker when the values get persisted to the database.

**Comment by AMekss** [comment]
Ok I think I got where the problem is - `:custom_authenticatable` overwriting password writer. Will fix this and roll out new version. Thanks for finding this.

**Comment by bennyzr** [comment]
I'm glad you found the issue. Looking through your code I can't see where you would be overwriting the password writer. The result of an empty password being persisted is that you can use any password and get authenticated. Do you think this is an expected behavior with Devise?

**Comment by bennyzr** [comment]
After further testing it looks like that when using :custom_authenticatable you can login without any password from any user account whether a password is on record or not.

**Comment by AMekss** [comment]
Override happens [here](https://github.com/AMekss/devise_custom_authenticatable/blob/master/lib/devise/models/custom_authenticatable.rb#L8)

Could you share how does `devise` setup and `valid_for_custom_authentication?` looks like in your User model?

**Comment by AMekss** [comment]
I just released version `0.3.1` which should address issue of password writer

**Comment by bennyzr** [comment]
Great I'll check it out. It seems that the database_autheticatable authentication is being short-circuited.
My User model is setup as follows:
```
class User < ApplicationRecord
devise :custom_authenticatable, :database_authenticatable, :recoverable, :trackable, :validatable, :timeoutable

	def valid_for_custom_authentication?(password)
		authenticated = false

		unless self.is_active?
			@custom_unauthenticated_message = "Account is not active"
		else
			unless self.user_login_ip_addresses.empty? || self.user_login_ip_addresses.exists?(ip_address: current_sign_in_ip)
				@custom_unauthenticated_message = "You can't login from your location"
			else
				authenticated = true
			end
		end

		return authenticated
  end
end
```

**Comment by AMekss** [comment]
I have to admit this is interesting use case. The problem with your code, since you don't really do any authentication here you should never return `true` from the method, as if you do it means devise let this user in as authenticated and auth request never reach next strategy. Instead you have to call `skip_custom_strategies` whenever you want to pass the request to `database_authenticatable`

I'd write something like this:
```ruby
def fail_authentication_with(custom_message)
  @custom_unauthenticated_message = custom_message
  false
end

def valid_location?
  user_login_ip_addresses.empty? || user_login_ip_addresses.exists?(ip_address: current_sign_in_ip)
end

def valid_for_custom_authentication?(_)
  return fail_authentication_with("Account is not active") unless is_active?
  return fail_authentication_with("You can't login from your location") unless valid_location?
  skip_custom_strategies
end
```

**Comment by bennyzr** [comment]
Ok, thanks for the clarification. I thought that the strategy was chained and returning true would pass execution to the next strategy without calling skip_custom_strategies.

**Comment by bennyzr** [comment]
Hi,

It seems that you can't set @custom_unauthenticated_message anymore. I get :invalid in resource.unauthenticated_message.

**Comment by AMekss** [comment]
Could you show how does `unauthenticated_message`, `valid_for_custom_authentication?` and related methods looks now in your User model?

**Comment by bennyzr** [comment]
I'm using the code you posted above 2 days ago..
