### ISSUE TITLE
Can't verify CSRF token authenticity.

### ISSUE THREAD

**Issue by bennyzr** [AMekss/devise_custom_authenticatable#9]
I recently upgraded to Rails 5.1.2 and can't login. I get a message "Can't verify CSRF token authenticity." and get redirected back to the login page. After some debugging I noticed that the Devise strategies are being run twice. Once before the Session create method and again during the create method. I think that the problem lies in that the strategies are being run twice. Any ideas?

**Comment by AMekss** [comment]
Are you running on the latest version of Devise? Does this happen only when `custom_authenticatable` module is enabled?

**Comment by bennyzr** [comment]
Yes. 4.3.0.

Actually it doesn't. 

That rules out your gem as being culpable. Sorry for bothering you about this.

**Comment by AMekss** [comment]
No worries, thanks :)
